server:
  port: 9120  #服务端口号
spring:
  application:
    name: gateway-service  #服务名称
  redis:
    host: 192.168.100.37        # Redis服务器地址
    port: 6379             # Redis服务器连接端口
    database: 0            # Redis数据库索引（默认为0）
    password:              # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200      # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10         # 连接池中的最大空闲连接
      min-idle: 0          # 连接池中的最小空闲连接
    timeout: 1000          # 连接超时时间（毫秒）
  cloud:
    gateway:
      globalauthfilter:
        open: true
        gateUrls[0]: /cds/
        gateUrls[1]: /moc/
        excludeUrls[0]: /cds/Login/odLogin     #登录接口
        excludeUrls[1]: /cds/msg/websocket     #websocket
        excludeUrls[2]: /cds/ws/
        excludeUrls[3]: /cds/img/              #静态图片
        excludeUrls[4]: /cds/Login/tempToken   #获取临时token
        excludeUrls[5]: /cds/dailyRunningReport/update
        excludeUrls[6]: /cds/dailyRunningReport/add
        excludeUrls[7]: /cds/dailyRunningReport/pushReport
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.37:9101/eureka/ #注册中心地址
# 设置请求允许访问域，这里配置对外发布的域名
nginxIpAddress: http://192.168.100.37  #nginx地址
